/**
 * Walk-forward backtest of the production model.
 *
 * GENERATED by scripts/backfill.mjs — do not edit by hand.
 * Every prediction counted here was made from ratings that existed before the
 * game was played, then graded against the final score.
 */

export const BACKTEST = {
  "generated_at": "2026-09-18T06:13:44.400Z",
  "model_version": "elo-mov-1.1",
  "source": "ESPN scoreboard API",
  "range": {
    "start": "2025-10-21",
    "end": "2026-06-27"
  },
  "games_fetched": 1322,
  "warmup_games_excluded": 150,
  "games_evaluated": 1172,
  "winner_accuracy": 67.8,
  "spread_accuracy": 52.9,
  "total_accuracy": 37.9,
  "correct_winners": 795,
  "correct_spreads": 620,
  "correct_totals": 444,
  "spread_mae": 11.52,
  "total_mae": 15.7,
  "brier_score": 0.2058
} as const;
